config/routes.rb
Rails.application.routes.draw do
  get 'menu' => 'menu#index'
  get 'contact' => 'welcome#contact'
  get 'search' => 'menu#search'
  resources :food_items do
    resources :orders
    resources :comments
  end
  root 'welcome#index'
  get 'thanks' => 'orders#thanks'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :food_item
end

app/models/food_item.rb
class FoodItem < ActiveRecord::Base
  is_impressionable :counter_cache => true, :unique => :all
  has_many :orders
  has_many :comments
  
  def self.filter_by_section(section)
  	where(section: section)
  end

  def self.filter_by_cuisine(cuisine)
    where(cuisine: cuisine)
  end
  
  def self.sort_by_name(name)
  	order(name: :ASC)
  end

  def self.sort_by_price(price)
    if price == "Increasing"
      order(price: :ASC)
    else
      order(price: :DESC)
    end
  end

  def self.sort_by_view(view)
    order('case when impressions_count is null then 0 else impressions_count end desc')
  end

  def url_or_auto
  	if url.present?
  		url
  	else
  		"http://loremflickr.com/320/240/#{name}"
  	end
  end

  def self.search(search)
    where("name LIKE ?", "%#{search}%") 
  end

end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :food_item
  DELIVERY_COST = 20
  COUPON_CODE = 'CODERSCHOOL'

  def total_cost
  	@factor = self.is_eligible_for_discount ? 0.5 : 1
  	FoodItem.find(self.food_item_id).price*@factor + DELIVERY_COST
  end

  def is_eligible_for_discount
  	self.coupon_code.upcase == COUPON_CODE
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
    @food_item = FoodItem.find(params[:food_item_id])
    @comment = @food_item.comments.create(comment_params)
    redirect_to food_item_path(@food_item)
  end
 
  private
    def comment_params
      params.require(:comment).permit(:commenter, :body)
    end
end

app/controllers/food_items_controller.rb
class FoodItemsController < ApplicationController
  before_action :set_food_item, only: [:show, :edit, :update, :destroy]
  # impressionist actions: [:show], unique: [:session_hash]
  # we're also making use of the :session_hash to keep track of unique views only.

  impressionist actions: [:show]
  # GET /food_items
  # GET /food_items.json
  def index
    @food_items = FoodItem.all
  end

  # GET /food_items/1
  # GET /food_items/1.json
  def show
  end

  # GET /food_items/new
  def new
    @food_item = FoodItem.new
  end

  # GET /food_items/1/edit
  def edit
  end

  # POST /food_items
  # POST /food_items.json
  def create
    @food_item = FoodItem.new(food_item_params)

    respond_to do |format|
      if @food_item.save
        format.html { redirect_to @food_item, notice: 'Food item was successfully created.' }
        format.json { render :show, status: :created, location: @food_item }
      else
        format.html { render :new }
        format.json { render json: @food_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /food_items/1
  # PATCH/PUT /food_items/1.json
  def update
    respond_to do |format|
      if @food_item.update(food_item_params)
        format.html { redirect_to @food_item, notice: 'Food item was successfully updated.' }
        format.json { render :show, status: :ok, location: @food_item }
      else
        format.html { render :edit }
        format.json { render json: @food_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /food_items/1
  # DELETE /food_items/1.json
  def destroy
    @food_item.destroy
    respond_to do |format|
      format.html { redirect_to food_items_url, notice: 'Food item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_food_item
      @food_item = FoodItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def food_item_params
      params.require(:food_item).permit(:name, :description, :price, :section, :url, :cuisine, :impressionist_count)
    end
end

app/controllers/menu_controller.rb
class MenuController < ApplicationController
  def index
  	@sections = %w(Breakfast Lunch Dinner Drinks)
    @cuisines = %w(Vietnamese Chinese Western)

    @items_by_section_default = FoodItem.order("created_at DESC").filter_by_section(params[:section])   #section
    @items_by_section_sorted_by_name = FoodItem.filter_by_section(params[:section]).sort_by_name(params[:name])
    @items_by_section_sorted_by_price =  FoodItem.filter_by_section(params[:section]).sort_by_price(params[:price])
    @items_by_cuisine = FoodItem.filter_by_cuisine(params[:cuisine])
    @items_sorted_by_view = FoodItem.sort_by_view(params[:view])

    if params[:name] == "name" 
      @items_sort = @items_by_section_sorted_by_name
    elsif params[:price].present? 
      @items_sort = @items_by_section_sorted_by_price
    elsif params[:cuisine].present? 
      @items_sort = @items_by_cuisine
    elsif params[:view].present? 
      @items_sort = @items_sorted_by_view
    else
      @items_sort = @items_by_section_default
    end 

  end
  
  def search
  	if params[:search].present?
      @items_by_search = FoodItem.search(params[:search])
    end
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
	def create
	    @food_item = FoodItem.find(params[:food_item_id])
	    @order = @food_item.orders.create(order_params)
	    # redirect_to food_item_path(@food_item)

	   if @order.save
	    redirect_to thanks_path(id: @order.id)
	   end
    end

    def thanks
    	@order = Order.find(params[:id])
    	@food_item = FoodItem.find(@order.food_item_id)
    end

 
  private
    def order_params
      params.require(:order).permit(:name, :number, :address, :email, :id, :coupon_code)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/food_items_helper.rb
module FoodItemsHelper
end

app/helpers/menu_helper.rb
module MenuHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/food_items/_comment_add.html.erb
<h2>Add a comment:</h2>
<%= form_for([@food_item, @food_item.comments.build]) do |f| %>
  <p>
    <%= f.label :commenter %><br>
    <%= f.text_field :commenter %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/food_items/_food_item.html.erb
<div class="card">
  <div class="card-block">
    <h4 class="card-title"><%= @food_item.name %></h4>
  </div>
  <%= image_tag @food_item.url_or_auto %>
  <div class="card-block">
    <p class="card-text"><%= @food_item.description %></p>
    <p class="card-text">PRICE: <%= @food_item.price %></p>
  </div>
</div>

app/views/food_items/_form.html.erb
<%= form_for(@food_item) do |f| %>
  <% if @food_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@food_item.errors.count, "error") %> prohibited this food_item from being saved:</h2>

      <ul>
      <% @food_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :section %><br>
    <%= f.text_field :section %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :cuisine %><br>
    <%= f.text_field :cuisine %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/food_items/_order.html.erb
<h2>ORDER</h2>
<%= form_for([@food_item, @food_item.orders.build]) do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :number %><br>
    <%= f.text_area :number %>
  </p>
  <p>
    <%= f.label :address %><br>
    <%= f.text_area :address %>
  </p>
  <p>
    <%= f.label :coupon %><br>
    <%= f.text_area :coupon_code %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/food_items/_show_comments.html.erb
<h2>Comments</h2>
<% @food_item.comments.each do |comment| %>
  <p>
    <strong>Commenter:</strong>
    <%= comment.commenter %>
  </p>
 
  <p>
    <strong>Comment:</strong>
    <%= comment.body %>
  </p>
<% end %>

app/views/food_items/_view_count.html.erb
<%= "#{@food_item.impressionist_count} views so far!" %>

app/views/food_items/edit.html.erb
<h1>Editing Food Item</h1>

<%= render 'form' %>

<%= link_to 'Show', @food_item %> |
<%= link_to 'Back', food_items_path %>

app/views/food_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Food Items</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Price</th>
      <th>Section</th>
      <th>Url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @food_items.each do |food_item| %>
      <tr>
        <td><%= food_item.name %></td>
        <td><%= food_item.description %></td>
        <td><%= food_item.price %></td>
        <td><%= food_item.section %></td>
        <td><%= image_tag food_item.url_or_auto %></td>
        <td><%= link_to 'Show', food_item %></td>
        <td><%= link_to 'Edit', edit_food_item_path(food_item) %></td>
        <td><%= link_to 'Destroy', food_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Food item', new_food_item_path %>

app/views/food_items/new.html.erb
<h1>New Food Item</h1>

<%= render 'form' %>

<%= link_to 'Back', food_items_path %>

app/views/food_items/show.html.erb
<%= render 'food_item' %>
<%= render 'view_count' %>
<%= render 'show_comments' %>
<%= render 'comment_add' %>
<%= render 'order' %>
<%= link_to 'Back to Menu', menu_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>EleganceRestaurant</title>
	  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	  <%= csrf_meta_tags %>
	</head>
	<body>
		<nav class="navbar navbar-light bg-faded">
		  <a class="navbar-brand" href="<%= root_path %>">Elegance Restaurant</a>
		  <ul class="nav navbar-nav">
		    <li class="nav-item active">
		      <a class="nav-link" href="<%= menu_path %>">Menu <span class="sr-only">(current)</span></a>
		    </li>
		    <li class="nav-item">
		      <a class="nav-link" href="<%= contact_path %>">Contact us</a>
		    </li>
		  </ul>
		</nav>
		<div class="container">
		  <%= yield %>
		</div>
	</body>
</html>

app/views/menu/_header.html.erb
<ul class="nav nav-pills">
  <% @sections.each do |section| %>
    <li class="nav-item">
    <%= link_to section, menu_path(section: section), class: "nav-link #{params[:section] == section ? 'active' : ''}" %>
    </li>
  <% end %>

  <li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Sort</a>
    <div class="dropdown-menu">
      <a class="dropdown-item" href="<%= menu_path(name: "name", section: params[:section]) %>">Alphabet</a>
      <a class="dropdown-item" href="<%= menu_path(price: "Increasing", section: params[:section]) %>">Price Up</a>
      <a class="dropdown-item" href="<%= menu_path(price: "Decreasing", section: params[:section]) %>">Price Down</a>
      <a class="dropdown-item" href="<%= menu_path(view: "Decreasing") %>">Most View</a>
    </div>
  </li>

  <li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Cuisine</a>
    <div class="dropdown-menu">
       <% @cuisines.each do |cuisine| %>
          <%= link_to cuisine, menu_path(cuisine: cuisine), class: "dropdown-item" %>
      <% end %>
    </div>
  </li>
</ul>

app/views/menu/_items.html.erb
<% @items_sort.each do |food_item| %>
  <div class="row">
    <div class="col-sm-4">
	    <table>
	      <tbody>
	        <tr>
            <td><%= link_to food_item.name, food_item %> </td>          
	          <td><span class="label label-pill label-primary"><%= food_item.price %></span></td>
	          <td><span class="label label-pill label-primary"><%= case when food_item.impressions_count.present? then food_item.impressions_count else 0 end %> view(s)</span></td>
	        </tr>
	      </tbody>
	    </table>
	</div>
	<div class="col-sm-4">
		<%= image_tag food_item.url_or_auto %>
	</div>
	<div class="col-sm-4">
		<%= food_item.description %>
	</div>	
  </div>
<% end %>

app/views/menu/_search.html.erb
<h1> Search Results </h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Price</th>
      <th>Section</th>
      <th>Url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @items_by_search.each do |food_item| %>
      <tr>
        <td><%= food_item.name %></td>
        <td><%= food_item.description %></td>
        <td><%= food_item.price %></td>
        <td><%= food_item.section %></td>
        <td><%= image_tag food_item.url_or_auto %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<h1> End of Search Results </h1>

app/views/menu/_search_engine.html.erb
<%= form_tag(search_path, :method => "get", id: "search-form", class: "form-inline pull-xs-right") do %>
  <%= text_field_tag :search, params[:search], placeholder: "Search.." %>
  <%= submit_tag "Search", class: "btn btn-success-outline" %>
<% end %>

app/views/menu/index.html.erb
<div class="container">
<%= render 'search_engine' %>
<%= render 'header' %>
<%= render 'items' %>
</div>

app/views/menu/search.html.erb
<h1> Menu Search </h1>

<% if @items_by_search.present? %>
    <%= render 'search' %>
  <% elsif params[:search] != nil %>
    <p>There is no food containing the term(s) <%= params[:search] %>.</p>
<% end %>

app/views/orders/thanks.html.erb
<div class="container">

<h1> Thanks. Here are the details of your order: </h1>
<%= render 'food_items/food_item' %>
<br/><br/><br/>
Your name: <%= @order.name %> <br/>
Your phone number: <%= @order.number %><br/>
Your Address: <%= @order.address %><br/>
Delivery Cost: <%= Order::DELIVERY_COST %><br/>
Total Cost: <%= @order.total_cost %><br/>
Discount: <%= @order.is_eligible_for_discount ? "50%" : "No discount" %><br/>
Date of order: <%= @order.created_at.strftime("%B %d, %Y") %><br/>
</div>

app/views/welcome/contact.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-4">
        <h1> Contact </h1>
        Address: Tân Phú,Hồ Chí Minh,Việt Nam<br/>
        Website: pizza4ps.com<br/>
		Tel: +84 120 460 4444<br/>
    </div>
    <div class="col-sm-8">
      <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d68154.83068931566!2d106.67181232066798!3d10.758954167967998!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0000000000000000%3A0x5f1b89599086065d!2sPizza+4P&#39;s!5e0!3m2!1svi!2s!4v1457885842197" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
    </div>
  </div>
</div>

app/views/welcome/index.html.erb
<h1>Elegance Restaurant</h1>

<div class="jumbotron">
  <h1 class="display-3">Welcome to Elegance</h1>
  <p class="lead">Enjoy your meal</p>
  <p class="lead">
    <div class="btn-group" role="group" aria-label="Basic example">
      <%= link_to 'Menu', menu_path, class: 'btn btn-secondary' %>
      <%= link_to 'Contact Us', contact_path, class: 'btn btn-secondary' %>
	</div>
  </p>
</div>